### ISSUE TITLE
Kimera docker

### ISSUE THREAD

**Issue by yasnem** [MIT-TESSE/goseek-challenge#29]
How can I use the Kimera pipeline from the goseek-kimera docker for training?
If I run the following command:
`docker run --rm -it --network=host --gpus all goseek-kimera /bin/bash -c "source /catkin_ws/devel/setup.bash && roslaunch tesse_gym_bridge run_goseek_perception.launch"` Shouldn't I be able to the see image data and meta data on port 9007 and 9008 on localhost and then set up the environment similar to here: [example](https://github.com/MIT-TESSE/tesse-gym-bridge/blob/master/notebooks/move-agent.ipynb)

**Comment by ZacRavichandran** [comment]
You would have to setup a gym environment, like the one in the example you linked, to consume data from the Kimera pipeline instead of directly from the simulator. You could check out [`test_locally.py`](https://github.com/MIT-TESSE/goseek-challenge/blob/master/test_locally.py) for reference. That outlines the requires steps of 1) starting the simulator 2) running the kimera docker container and 3) running the gym environment. This [config](https://github.com/MIT-TESSE/goseek-challenge/blob/master/config/perception-pipeline.yaml) is used to point the gym environment to the correct ports (9007 and 9008, as you've noted).
